// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOwNGvSgf-pi_ce7kIf1ynQ35li3Xl5yo',
    appId: '1:719566449623:web:ab5824fc7c87481712b992',
    messagingSenderId: '719566449623',
    projectId: 'todo-list-50911',
    authDomain: 'todo-list-50911.firebaseapp.com',
    storageBucket: 'todo-list-50911.appspot.com',
    measurementId: 'G-TQRT7JBQD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67_GUjzlFgQktuQ-H4re_htIAZEmIAyQ',
    appId: '1:719566449623:android:6209181ac55eff6412b992',
    messagingSenderId: '719566449623',
    projectId: 'todo-list-50911',
    storageBucket: 'todo-list-50911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7KL1CeUnKQH_tEnyF2t9UuCXRa1yHVI',
    appId: '1:719566449623:ios:280b44692ea3e4db12b992',
    messagingSenderId: '719566449623',
    projectId: 'todo-list-50911',
    storageBucket: 'todo-list-50911.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7KL1CeUnKQH_tEnyF2t9UuCXRa1yHVI',
    appId: '1:719566449623:ios:6a76e93cff2b766f12b992',
    messagingSenderId: '719566449623',
    projectId: 'todo-list-50911',
    storageBucket: 'todo-list-50911.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
